platform :ios, '8.0'

target 'LiuHe' do
pod 'AFNetworking', '~>3.0'
pod 'SDWebImage', '~>3.8'
pod 'MJRefresh'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/UI'
end
