platform :ios, '8.0'

target 'LiuHe' do
pod 'AFNetworking', '~>3.0'
pod 'SDWebImage', '~>3.8'
pod 'MJRefresh'
pod 'MBProgressHUD', '~>1.0.0'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/UI'
pod 'FMDB'
end
